
flib_version=0.2.8
flib_file=8482026


mod_id=shiftclickvillagertrading
curse_slug=shiftclickvillagertrading
modrinth_id=
curse_id=0
mod_version=0.0.0-SNAPSHOT
mod_name=shiftclickvillagertrading
mod_group_id=com.lothrazar.shiftclickvillagertrading
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=shiftclickvillagertrading
